#!/bin/bash
# start.sh
# Copyright (C) 2020 wanghch <wanghch@wanghch-pc>
#
# Distributed under terms of the MIT license.
#
bin=`dirname "$0"`
export APP_DIR=`cd "$bin/"; pwd`
. $APP_DIR/bin/conf.sh

run_action $@
